#define VERSION_FILEVERSION_NUM     	0,2,0,0
#define VERSION_FILEVERSION_SHORT   	L"0.2.0"
#define VERSION_FILEVERSION_LONG    	L"Notepatch 0.2.0"
#define VERSION_LEGALCOPYRIGHT_SHORT	L"Copyright © 2025"
#define VERSION_LEGALCOPYRIGHT_LONG 	L"© 59de44955ebd 2025"
#define VERSION_FILEDESCRIPTION     	L"Notepatch"
#define VERSION_INTERNALNAME        	L"Notepatch"
#define VERSION_ORIGINALFILENAME    	L"Notepatch.exe"
#define VERSION_AUTHORNAME          	L"59de44955ebd"
#define VERSION_WEBPAGEDISPLAY      	L"https://github.com/59de44955ebd/Notepatch"
#define VERSION_DESCRIPTION				L"A small and simple clone of Windows Notepad with some fixes and enhancements"
